version: "3.7"
 
services:
  udility:
    build: .
    depends_on:
      lavalink:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm start
    restart: always
    links:
      - lavalink

  lavalink:
    build:
      context: .
      dockerfile: Dockerfile.lavalink
    restart: always
    healthcheck:
      test: 'echo lavalink'
  redis:
    image: redis:6.2.6-alpine
    container_name: redis-dis
    restart: always
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local


