version: "3.7"
 
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-app-dev
    volumes:
      # - /app/node_modules
      - ./src:/app/src
    ports:
      - "8080:8080"
      - "8181:8181"
    command: npm run dev