version: "3.7"
 
services:
  udility:
    build: .
    depends_on:
      lavalink:
        condition: service_healthy
    command: npm start
    links:
      - lavalink
  lavalink:
    image: fredboat/lavalink:dev
    volumes:
      - ./application/application.yml:/opt/Lavalink/application.yml
    healthcheck:
      test: 'echo lavalink'

