name: Docker image runner

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        env:
          NODE_ENV: 'production'
          TOKEN: ${{ secrets.TOKEN }}
          LAVA_HOST: 'lavalink'
          LAVA_PASS: 'youshallnotpass'
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          cat <<EOF > .env
          NODE_ENV=$NODE_ENV
          TOKEN=$TOKEN
          LAVA_HOST=$LAVA_HOST
          LAVA_PASS=$LAVA_PASS
          SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
          SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
          EOF

          echo "cat .env"
          cat .env

      - name: Rebuild Image and start container
        run: sudo docker-compose up -d --build
